name: Crawler Crucemundo

on:
  workflow_dispatch:

jobs:
  ejecutar:

    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          pip install playwright beautifulsoup4 requests google-auth google-api-python-client
          playwright install chromium

      - name: Ejecutar crawler
        run: |
          python crawler_crucemundo.py
